hostname = dubai.aihuishou.com, sr.aihuishou.com

^https:\/\/dubai\.aihuishou\.com\/ahs-yanxuan-service\/products\/search-goods-v2 url script-response-body https://raw.githubusercontent.com/liangpengfeng/aihuishou-filter/main/aihuishou_filter.js
